### ISSUE TITLE
Disable Coil plug-in monetization while on my own sites/pages

### ISSUE THREAD

**Issue by disquisitioner** [interledger/web-monetization-projects#1159]
I'm using the Coil plugin on Firefox and would like to be able to disable monetization of my own sites/pages while I'm visiting them. This would be useful in general, and especially so while I'm developing, testing, and staging new pages for my sites.  Seems like it'd be straightforward to include in the Coil plug-in's settings my own payment pointer and have the plug-in not actively monetize on any page specifying that payment pointer.

In addition to avoiding the payment indications in the plug-in UX and the spurious payments themselves, this would avoid me getting a stream of notification messages from my wallet provider that my site is generating payments especially many such notifications over extended periods of time when I'm building pages, staging, and testing new site content. 

Lacking such a feature in the plug-in I've had to incorporate something that approximates it as a page-level property and remember to turn it properly on/off when I'm finally ready for a new page to go live in production.

**Comment by sublimator** [comment]
@disquisitioner 

Thanks for the feedback and suggestions. 

I guess the first minimalist step we could take is to automatically disable it, when the payment pointer is unambiguously yours. We could add something in a settings page to disable monetization for certain url patterns, which would cover both Payment Pointers (expanded to urls) and browsed pages themselves. 

@sharafian ?

**Comment by disquisitioner** [comment]
Thanks @sublimator -- Automatically disabling payments when the pointer is unambiguously mine would be fine.  The browser plug-in already has a settings page that contains my personal info, so entering my payment pointer there seems reasonable and straightforward.   Disabling monetizing my own sites seems like something I'd pretty much always want to be true so I wouldn't be back and forth into the plugin's settings to switch it on and off. 

A filter list of "don't monetize" payment pointers and URL patterns would offer additional benefits, but FWIW I'd see making that a feature with separate configuration controls, etc. in the plug-in.

**Comment by sublimator** [comment]
Noted, we'll see what we can do!

**Comment by sublimator** [comment]
@disquisitioner 

I had a quick look into simply automatically disabling payment to your own payment pointer, but then realized a lot of people will want to test their sites with the extension. This would require some UI to enable it for those times. 

That will require more extensive input from the product/design team. Coil is also soon coming out with a new product that will allow its users to create many different payment pointers, which will require extra consideration. 

We'll have to wait and see.

**Comment by disquisitioner** [comment]
@sublimator 

Thanks for the update.  Disappointing that this isn't something that could get into the extension any time soon. I can understand the benefit of being able to enable/disable "self payments" but that seems like a simple addition to the extension settings page alongside the setting to be added to let you enter your own payment pointer.  The extension settings panel is pretty bare bones at the moment.

As for the new Coil product, do you know when that's expected to release?  I hate for that to be several months from now and hold up a useful and straightforward feature for the current extension.  Certainly supporting multiple payment pointers would change the UI, and allowing individual payment pointers to be enabled/disabled change that further.   Still, having a UX for that now would add value to the extension and let you prove out a more sophisticated version for later on.

In the short term I can enable/disable the Coil extension through the simple interface my browser provides for managing extensions, so I'll have to do that.  I don't think that's a great solution as it means I might not always have the Coil extension enabled when I'm browsing the web, and it likely won't be on by default in all my browsers as I'd like it to be, which would negatively impact monetization for sites I visit.

I'll stay tuned to see how things play out here.

**Comment by sublimator** [comment]
@disquisitioner 

I'll see about taking a stab at this myself as it would serve as good starting point for the product/design team and will be largely recyclable. If you don't mind building/installing the extension from source you will be able to get access early.

**Comment by disquisitioner** [comment]
@sublimator 

Thanks -- that sounds like a good approach.  I'd be happy to build/install the extension from source and help test it out.  Much appreciated.

**Comment by sublimator** [comment]
@disquisitioner 

Hi, I took a stab at disabling last week. It's still a WIP (disabling settings only stored in memory), but if you'd like to try it out now, I made a snapshot branch:
https://github.com/coilhq/web-monetization-projects/tree/nd-disabling-snapshot-2020-11-02

We have a document for building the extension aimed at designers that may prove of use:
https://github.com/coilhq/web-monetization-projects/blob/main/packages/coil-extension/docs/building-extension-for-designers.md

Let me know what you think/any questions etc.

Thanks!

**Comment by disquisitioner** [comment]
Excellent, and especially appreciate the document for building the extension.  I'll sit down at my Mac, give it a try, and let you know what happens.

**Comment by sublimator** [comment]
> appreciate the document 

You're welcome :)

**Comment by sublimator** [comment]
@disquisitioner 

Hi, did you get a chance amongst all the excitement to build from source?

**Comment by disquisitioner** [comment]
@sublimator 

You're right -- it's been quite a week!  I finally had a quiet moment today to give it a try, which took a bit of setup as I don't use Chrome and didn't have it installed.  The 'Building Extension for Designers' document made the process easy to follow.  I got to the point where I attempted to build the extension ('yarn dev-chrome-prod') and encountered an error complaining the module 'setImmediate' could not be found.  I can send you the output from yarn with the various diagnostic messages if that helps.  More than happy to troubleshoot so I can keep going to build and test the new extension.  Thanks!

**Comment by sublimator** [comment]
@disquisitioner 

I missed your reply sorry.  (It's also gotten some value of exciting over here in Cambodia. As fate would have it, on November the 3rd the PM went into quarantine and schools have been closed again :/)

>> encountered an error complaining the module 'setImmediate' could not be found

That sounds like something to do with the recent upgrade to webpack 5. They removed all the nodejs polyfills which use to work by default. In principle I try to keep up to date with all the tools as they come out, to keep the bitrot away. ~~The only thing I can think of as I'm writing is that maybe you ran `yarn install` on the "main" branch, then switched to the other branch, without running "yarn install" again. But actually, our build script runs "yarn install" as part of each build unless skipped via SKIP_YARN env var, which I set as the few seconds is annoying enough to want .....~~ 

In any case: 
1. I'll create another snapshot branch for you
2. Google finally allowed me to publish an "unlisted" CoilDev extension with a secret link

**Comment by sublimator** [comment]
> I don't use Chrome and didn't have it installed

Yeah, sorry about that. I'm primarily a Chrome user by entrenched habit. 
Generally only fire it up for when I go through the release checklist. 
Am going to look into FF more soon, in particular on android. 
Will see about publishing a CoilDev on the Mozilla add-ons store then.

**Comment by sublimator** [comment]
@disquisitioner 

I emailed you a link to the CoilDev extension.
Let me know if there's anything else! 

Cheers :)
