### ISSUE TITLE
Extension icon state does not change when payment pointer changes

### ISSUE THREAD

**Issue by Danisco212** [interledger/web-monetization-projects#3187]
If the payment pointer url changes on the webpage, the extension state icon doesn't change unless the webpage is out of focus and refocused

**Comment by sublimator** [comment]
Can you give an explicit example of a change?

**Comment by Danisco212** [comment]
Changing the href through code something like this
`const link = document.querySelector('link[rel="monetization"]')
 link.href= "https://google.com"
`

The icon remains with a full green icon, and the popup states its still paying out
<img width="406" alt="image" src="https://user-images.githubusercontent.com/58591021/182569775-adf82380-dc18-4d8d-8d75-3bd4d9055316.png">
