### ISSUE TITLE
Contact Mozilla to be listed on FF add-ons store

### ISSUE THREAD

**Issue by sublimator** [interledger/web-monetization-projects#968]
![image](https://user-images.githubusercontent.com/525211/91781946-e3527b00-ec25-11ea-85fc-b32a0e1586a0.png)

I am sure this used to be possible

**Comment by traviscrist** [comment]
Which link is used here, is it? https://addons.mozilla.org/en-US/android/addon/coil/

**Comment by sublimator** [comment]
We chatted out of band, but for the record, no joy installing with explicitly android link, with both FF and FF Nightly.

**Comment by njlie** [comment]
I checked the extension's product page with our Mozilla dev account, where it says it's been approved for Firefox for Android...

**Comment by sublimator** [comment]
Anyone else with an android can check?

**Comment by sublimator** [comment]
https://palant.info/2020/08/31/a-grim-outlook-on-the-future-of-browser-add-ons/

**Comment by sharafian** [comment]
https://support.mozilla.org/en-US/kb/find-and-install-add-ons-firefox-android?redirectslug=add-compatibility-firefox-preview&redirectlocale=en-US

**Comment by sharafian** [comment]
> Will more extensions be supported in the future?

> We would like to enable support for more extensions on the new Firefox for Android experience and we are currently evaluating ways we can do so without introducing the compatibility and security issues from the previous version of our mobile browser for Android. We'll provide updates as soon as we have more details. 

It sounds like they may, at some point, allow any extension to be installed in firefox for android, but it's unlikely that if they expand it they'll allow permissions as flexible as Coil requires. I guess we should see if we can get in their allowed list?

**Comment by sublimator** [comment]
For record: asked @cyberdees and Ali on Oct 8th

**Comment by Utopiah** [comment]
Please have a look at the [Recommended Extensions Program](https://extensionworkshop.com/documentation/publish/recommended-extensions/) with contact in the last paragraph.

With particular attention to :
- Does the extension function at an exemplary level?
- Is the extension safe?
- Does the extension offer an exceptional user experience? 
- Is the extension relevant to a general, international audience? 

If you believe it's clearly fulfilling those criteria feel free to contact  amo-featured [at] mozilla [dot] org.

**Comment by sublimator** [comment]
@Utopiah 

Thanks for that. There are a few rough spots discovered since this issue was open. It seems a few android specific workarounds we had were broken in the new FF version.

**Comment by wmurphyrd** [comment]
@sublimator I hope you'll consider submitting to Firefox Recommended Extensions program. I believe the blocking issues when this was raised before were the CSP-related issues that can since been resolved (#1248). 

On the WebXR front, we've got a new (or rather resurrected) [Firefox-based browser](https://www.igalia.com/2022/02/03/Introducing-Wolvic.html) for android-based VR devices that this would be really valuable for.
